name: 'PagerDuty Notifier'
description: 'Send alert notification to PagerDuty on Pull Request'
inputs:
  severity:
    description: 'Level of severity of the alert (warning, critical, etc)'
    required: true
    default: 'warning'
  source:
    description: 'Human-readable unique identifier for the system having the problem'
    required: true
    default: 'Unknown Github Repo Pull Request'
  summary:
    description: 'A high-level, text summary message of the event used to construct an alert's description.'
    required: true
    default: 'Pull Request Created'
runs:
  using: 'docker'
  image: 'Dockerfile'
   env:
     PAGERDUTY_API_TOKEN: ${{ secrets.PAGERDUTY_API_TOKEN }}
     PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
     PAGERDUTY_SEVERITY: ${{ inputs.severity }}
     PAGERDUTY_SOURCE: ${{ inputs.source }}
     PAGERDUTY_SUMMARY: ${{ inputs.summary }}
